server {
    listen 80;
    listen [::]:80;
    server_name www.mereed.dev;

    return 301 https://mereed.dev$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name mereed.dev;

    return 301 https://mereed.dev$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.mereed.dev;

    ssl_certificate /etc/letsencrypt/live/mereed.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mereed.dev/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://mereed.dev$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name mereed.dev;

    root /var/www/mereed.dev;
    index index.html;

    access_log /var/log/nginx/mereed.dev.access.log;
    error_log /var/log/nginx/mereed.dev.error.log;

    ssl_certificate /etc/letsencrypt/live/mereed.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mereed.dev/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ =404;
    }
}
